services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: balance-processor
    ports:
      - "${BP_SERVER_PORT:-8080}:${BP_SERVER_PORT:-8080}"
    volumes:
      - ./configs:/app/configs
    environment:
      - BP_DB_HOST=${BP_DB_HOST:-postgres}
      - BP_DB_PORT=${BP_DB_PORT:-5432}
      - BP_DB_USERNAME=${BP_DB_USERNAME:-postgres}
      - BP_DB_PASSWORD=${BP_DB_PASSWORD:-postgres}
      - BP_DB_NAME=${BP_DB_NAME:-balance_processor}
      - BP_DB_SSL_MODE=${BP_DB_SSL_MODE:-disable}
      - BP_DB_MAX_OPEN_CONNS=${BP_DB_MAX_OPEN_CONNS:-200}
      - BP_DB_MAX_IDLE_CONNS=${BP_DB_MAX_IDLE_CONNS:-100}
      - BP_DB_CONN_MAX_LIFETIME_MINUTES=${BP_DB_CONN_MAX_LIFETIME_MINUTES:-30}
      - BP_DB_CONN_MAX_IDLE_TIME_MINUTES=${BP_DB_CONN_MAX_IDLE_TIME_MINUTES:-15}
      - BP_DB_QUERY_TIMEOUT_SECONDS=${BP_DB_QUERY_TIMEOUT_SECONDS:-5}
      - BP_DB_RETRY_ATTEMPTS=${BP_DB_RETRY_ATTEMPTS:-3}
      - BP_DB_RETRY_DELAY_SECONDS=${BP_DB_RETRY_DELAY_SECONDS:-1}
      - BP_SERVER_PORT=${BP_SERVER_PORT:-8080}
      - BP_TRANSACTION_CONCURRENCY_LEVEL=${BP_TRANSACTION_CONCURRENCY_LEVEL:-200}
      - BP_TRANSACTION_LOCK_TIMEOUT_MS=${BP_TRANSACTION_LOCK_TIMEOUT_MS:-5000}
      - BP_TRANSACTION_MAX_RETRIES=${BP_TRANSACTION_MAX_RETRIES:-3}
      - BP_LOGGER_LEVEL=${BP_LOGGER_LEVEL:-info}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G

  postgres:
    image: postgres:16-alpine
    container_name: balance-processor-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-balance_processor}
      # PostgreSQL performance tuning
      - POSTGRES_SHARED_BUFFERS=256MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=512MB
      - POSTGRES_WORK_MEM=16MB
      - POSTGRES_MAINTENANCE_WORK_MEM=128MB
      - POSTGRES_MAX_CONNECTIONS=300
      - POSTGRES_MAX_PARALLEL_WORKERS=8
      - POSTGRES_MAX_WORKER_PROCESSES=8
      - POSTGRES_SYNCHRONOUS_COMMIT=off
    command: >
      postgres
        -c shared_buffers=256MB
        -c effective_cache_size=512MB
        -c work_mem=16MB
        -c maintenance_work_mem=128MB
        -c max_connections=300
        -c max_parallel_workers=8
        -c max_worker_processes=8
        -c synchronous_commit=off
        -c random_page_cost=1.1
        -c effective_io_concurrency=200
        -c checkpoint_timeout=30
        -c max_wal_size=1GB
        -c default_statistics_target=100
    ports:
      - "${POSTGRES_PORT:-15432}:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 