server:
  host: "0.0.0.0"  # Can be overridden by BP_SERVER_HOST
  port: 8080       # Can be overridden by BP_SERVER_PORT
  readTimeout: 10    # seconds
  writeTimeout: 15   # seconds
  idleTimeout: 120   # seconds
  readHeaderTimeout: 5  # seconds
  shutdownTimeout: 10  # seconds

database:
  driver: "postgres"
  # These sensitive values should be provided through environment variables
  host: ""         # Set via BP_DB_HOST
  port: ""         # Set via BP_DB_PORT
  username: ""     # Set via BP_DB_USERNAME
  password: ""     # Set via BP_DB_PASSWORD
  database: ""     # Set via BP_DB_NAME
  sslMode: "require"  # Can be overridden by BP_DB_SSL_MODE
  maxOpenConns: 100
  maxIdleConns: 20
  connMaxLifetime: 30   # minutes
  connMaxIdleTime: 5    # minutes
  queryTimeout: 60      # seconds
  retryAttempts: 5      # Number of retry attempts for database operations
  retryDelay: 5         # Delay between retries in seconds

logger:
  level: "info"     # Can be overridden by BP_LOGGER_LEVEL
  format: "json"
  output: "stdout"
  timeFormat: "2006-01-02T15:04:05.000Z07:00"
  callerInfo: true

transaction:
  concurrencyLevel: 100    # Can be overridden by BP_TRANSACTION_CONCURRENCY_LEVEL
  lockTimeoutMs: 10000     # Can be overridden by BP_TRANSACTION_LOCK_TIMEOUT_MS
  maxRetries: 3            # Maximum number of retries for failed transactions
  userBalanceDecimalPlaces: 2  # Decimal places for user balance 